// <auto-generated />
using DataProcessorService.MyDbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataProcessorService.Migrations
{
    [DbContext(typeof(SQLiteDataBase))]
    [Migration("20231215085253_Mig_1")]
    partial class Mig_1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.25");

            modelBuilder.Entity("DataProcessorService.ModuleCategoreIDModeleState", b =>
                {
                    b.Property<int>("ModuleCategoreIDModeleStateID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModeleState")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ModuleCategoreID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ModuleCategoreIDModeleStateID");

                    b.HasIndex("ModuleCategoreID")
                        .IsUnique();

                    b.ToTable("ModuleCategoreIDModeleStates");
                });
#pragma warning restore 612, 618
        }
    }
}
